#!/bin/bash

# Local Supabase Setup Script
# Sets up self-hosted Supabase on your Mac using Docker

set -e

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'

print_success() { echo -e "${GREEN}✅ $1${NC}"; }
print_warning() { echo -e "${YELLOW}⚠️  $1${NC}"; }
print_error() { echo -e "${RED}❌ $1${NC}"; }
print_info() { echo -e "${BLUE}ℹ️  $1${NC}"; }

echo "🚀 Local Supabase Setup"
echo "================================"
echo ""

# ============================================================================
# Step 1: Check Docker
# ============================================================================

echo "Step 1: Checking Docker..."
if command -v docker &> /dev/null; then
    if docker info &> /dev/null; then
        print_success "Docker is running"
    else
        print_error "Docker is installed but not running!"
        echo ""
        echo "Please start Docker Desktop and try again"
        echo "You can find Docker Desktop in Applications"
        exit 1
    fi
else
    print_error "Docker is not installed!"
    echo ""
    echo "Installing Docker Desktop..."
    echo "Opening download page..."
    open "https://www.docker.com/products/docker-desktop"
    echo ""
    echo "After installation:"
    echo "  1. Open Docker Desktop"
    echo "  2. Wait for it to start (whale icon in menu bar)"
    echo "  3. Run this script again: ./setup-local-supabase.sh"
    exit 1
fi

# ============================================================================
# Step 2: Install Supabase CLI
# ============================================================================

echo ""
echo "Step 2: Installing Supabase CLI..."

if command -v supabase &> /dev/null; then
    print_success "Supabase CLI already installed"
else
    if command -v brew &> /dev/null; then
        brew install supabase/tap/supabase
        print_success "Supabase CLI installed"
    else
        print_error "Homebrew not found!"
        echo "Installing Homebrew..."
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        brew install supabase/tap/supabase
    fi
fi

# ============================================================================
# Step 3: Initialize Supabase
# ============================================================================

echo ""
echo "Step 3: Initializing local Supabase..."

if [ -d "supabase" ]; then
    print_warning "Supabase already initialized (supabase/ folder exists)"
else
    supabase init
    print_success "Supabase initialized"
fi

# ============================================================================
# Step 4: Start Supabase
# ============================================================================

echo ""
echo "Step 4: Starting Supabase containers..."
echo "(This may take 2-3 minutes on first run - downloading Docker images)"
echo ""

supabase start

print_success "Supabase is running!"

# ============================================================================
# Step 5: Get credentials and update .env
# ============================================================================

echo ""
echo "Step 5: Saving credentials..."

# Get the status output
STATUS=$(supabase status)

# Extract credentials
API_URL=$(echo "$STATUS" | grep "API URL" | awk '{print $3}')
ANON_KEY=$(echo "$STATUS" | grep "anon key" | awk '{print $3}')
SERVICE_KEY=$(echo "$STATUS" | grep "service_role key" | awk '{print $3}')

# Update .env file
cat > .env <<EOF
# Local Supabase Configuration
# Auto-generated by setup-local-supabase.sh

SUPABASE_URL=$API_URL
SUPABASE_ANON_KEY=$ANON_KEY
SUPABASE_SERVICE_KEY=$SERVICE_KEY

# This is a LOCAL instance - safe to commit these keys
# They only work on your machine (localhost)
EOF

print_success ".env file updated with local credentials"

# Update web config
cat > web/config.js <<EOF
// Local Supabase Configuration
// Auto-generated - safe for local development

const SUPABASE_URL = '$API_URL';
const SUPABASE_ANON_KEY = '$ANON_KEY';

window.SUPABASE_CONFIG = {
    url: SUPABASE_URL,
    anonKey: SUPABASE_ANON_KEY
};
EOF

print_success "web/config.js updated"

# ============================================================================
# Step 6: Apply database schema
# ============================================================================

echo ""
echo "Step 6: Creating database tables..."

# Copy schema to supabase migrations folder
mkdir -p supabase/migrations
TIMESTAMP=$(date +%Y%m%d%H%M%S)
cp database/schema.sql "supabase/migrations/${TIMESTAMP}_initial_schema.sql"

# Apply migration
supabase db reset

print_success "Database schema applied!"

# ============================================================================
# Display Info
# ============================================================================

echo ""
echo "================================"
echo "✅ Local Supabase is Ready!"
echo "================================"
echo ""
echo "📊 Access Points:"
echo ""
echo "  🌐 Studio (Web UI):  http://localhost:54323"
echo "  🔌 API URL:          $API_URL"
echo "  📊 Database:         postgresql://postgres:postgres@localhost:54322/postgres"
echo ""
echo "🔑 Credentials (saved to .env):"
echo "  Anon Key:     $ANON_KEY"
echo "  Service Key:  $SERVICE_KEY"
echo ""
echo "================================"
echo ""
echo "📋 Next Steps:"
echo ""
echo "1. Open Supabase Studio:"
echo "   → http://localhost:54323"
echo "   → Check that tables exist (clients, payments, lessons)"
echo ""
echo "2. Export Google Sheets as CSV to database/exports/"
echo ""
echo "3. Run migration:"
echo "   → ./migrate.sh"
echo ""
echo "4. Test web interface:"
echo "   → open web/index.html"
echo ""
echo "================================"
echo ""
print_info "To stop Supabase: supabase stop"
print_info "To start again: supabase start"
print_info "Studio will auto-open in your browser..."
echo ""

# Open Studio
sleep 2
open "http://localhost:54323"
